version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs: 
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install syntax-error --no-package-lock --no-save --also=dev
      - run:
          name: Run test using nodejs << parameters.node-version >>
          command: node test.js
        
workflows:
  all-test:
    jobs:
      - test: 
          matrix:
            parameters:
              node-version: ['14.19', '16.14', '17.5']
